config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'students',passwords: 'users/passwords'}
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new'
    post 'users/sign_in', to: 'users/sessions#create'
    get 'users/sign_out', to: 'users/sessions#destroy'
    get 'users/sign_up', to: 'users/registrations#new'
    post 'users/sign_up', to: 'users/registrations#create'
    get "student_home", to: 'students#index'
    get "add_subject", to: 'students#add_subject'
    patch "change_subject_request", to: 'students#change_subject_request'
    get "change_password", to: 'users/registrations#change_password'
    patch 'change_my_password', to: 'users/registrations#change_my_password'
    authenticated :user do
      root to: 'application#dashboard'
    end
    unauthenticated do
      root to: "users/sessions#new", as: nil
    end
  end
  
  get "admin_home", to: "admins#index"
  get "all_user", to: "admins#all_user"
  get "subject_wise_students_count", to: "admins#subject_wise_students_count"
  get "user_details", to: "admins#user_details"
  post "user_verify", to: "admins#user_verify"
  post "user_delete", to: "admins#user_delete"
  post "save_mass_data_upload", to: "admins#save_mass_data_upload" 
  post "add_student", to: "admins#add_student"
  get "get_student_data", to: "admins#get_student_data"
  post "update_student", to: "admins#update_student"
end

app/views/admins/_add_student_data.html.erb
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header" style="margin: 0px 0px 10px 20px; display: flex;">
            <h4 class="modal-title">Add Student</h4>
            <span style="margin-left: auto; cursor: pointer;" onclick="modalClose('addModal')">
                <i class="fa-solid fa-xmark fa-2xl"></i>
            </span>
        </div>
        <div class="modal-body">
            <div class="container" style="max-width: 550px; ">
                <%= form_for(current_user, url: add_student_path, html: { method: :post }) do |f| %>
                <%= render "devise/shared/error_messages", resource: current_user %>
                    <% if alert %>
                        <p class="alert alert-danger"><%= alert %></p>
                    <% end %>
                    <div class="row">
                        <div class="col-md-6">
                        <div class="field">
                            <%= f.label :email %>
                            <%= f.email_field :email, id: "email", autofocus: true, autocomplete: "email", placeholder: "Enter your email", required: true %>
                        </div>
                        </div>

                        <%= f.fields_for :student do |s| %> 
                        <div class="col-md-6">
                            <div class="field">
                            <%= s.label :name %>
                            <%= s.text_field :name, id: "name", placeholder: "Enter your full name", required: true %>
                            </div>
                        </div>
                    </div>

                        <div class="row">
                            <div class="col-md-6">
                            <%= s.fields_for :profile do |sp| %>
                            <div class="field">
                                <%= sp.label :avatar, "Image" %>
                                <%= sp.file_field :avatar, accept: 'image/*', placeholder: "Choose an avatar image", id: 'avatar-input' %>
                            </div>
                            </div>
                        
                            <div class="col-md-6">
                            <div class="field">
                                <%= sp.label :bio %>
                                <%= sp.text_field :bio, placeholder: "Enter your bio", id: "bio", required: true %>
                            </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                            <div class="field">
                                <%= sp.label :dob, "Date of Birth" %>
                                <%= sp.date_field :dob, placeholder: "Select your date of birth", id: "dob", required: true %>
                            </div>
                            </div>
                    
                            <div class="col-md-6">
                            <div class="field">
                                <%= sp.label :gender %>
                                <%= sp.select :gender, ["Male", "Female", "Other"], { prompt: "Select your gender" }, { include_blank: false, required: true, id: "gender" } %>

                            </div>
                            <% end %>
                            </div>
                        </div>

                        <%= s.fields_for :address do |sa| %>
                        
                        <div class="row">
                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :street, "Address" %>
                                <%= sa.text_field :street, id: "street", placeholder: "Enter your full address", required: true %>
                            </div>
                            </div>

                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :city %>
                                <%= sa.text_field :city, id: "city", placeholder: "Enter your city", required: true %>
                            </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :state %>
                                <%= sa.text_field :state, id: "state", placeholder: "Enter your state", required: true %>
                            </div>
                            </div>

                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :pin %>
                                <%= sa.text_field :pin, id: "pin", placeholder: "Enter your PIN code", required: true %>
                            </div>
                            </div>
                        </div>

                        <% end %>
                    <% end %>
                
                <div class="actions">
                    <%= f.button "Cancel", class: "btn btn-danger", type: "button", onclick: "modalClose('addModal')", style: "padding: 10px 20px;" %>
                    <%= f.submit "Add", class: "btn btn-success", style: "padding: 10px 30px;" %>
                </div>
                <% end %>  
            </div>
        </div>
    </div>
</div>

app/views/admins/_edit_student_data.html.erb
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header" style="margin: 0px 0px 10px 20px; display: flex;">
            <h4 class="modal-title">Edit Student</h4>
            <span style="margin-left: auto; cursor: pointer;" onclick="modalClose('editModal')">
                <i class="fa-solid fa-xmark fa-2xl"></i>
            </span>
        </div>
        <div class="modal-body">
            <div class="container" style="max-width: 550px; ">
                <%= form_for(current_user, url: update_student_path, html: { method: :post }) do |f| %>
                <%= render "devise/shared/error_messages", resource: current_user %>
                    <%= f.hidden_field :id, id: "userID" %>
                    <div class="row">
                        <div class="col-md-6">
                        <div class="field">
                            <%= f.label :email %>
                            <%= f.email_field :email, id: "editEmail", required: true %>
                        </div>
                        </div>

                        <%= f.fields_for :student do |s| %> 
                        <div class="col-md-6">
                            <div class="field">
                            <%= s.label :name %>
                            <%= s.text_field :name, id: "editName", placeholder: "Enter your full name", required: true %>
                            </div>
                        </div>
                    </div>

                        <div class="row">
                            <div class="col-md-6">
                            <%= s.fields_for :profile do |sp| %>
                            <div class="field">
                                <%= sp.label :avatar, "Image" %>
                                <%= sp.file_field :avatar, accept: 'image/*', placeholder: "Choose an avatar image", id: 'avatar' %>
                            </div>
                            </div>
                        
                            <div class="col-md-6">
                            <div class="field">
                                <%= sp.label :bio %>
                                <%= sp.text_field :bio, placeholder: "Enter your bio", id: "editBio", required: true %>
                            </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                            <div class="field">
                                <%= sp.label :dob, "Date of Birth" %>
                                <%= sp.date_field :dob, placeholder: "Select your date of birth", id: "editDob", required: true %>
                            </div>
                            </div>
                    
                            <div class="col-md-6">
                            <div class="field">
                                <%= sp.label :gender %>
                                <%= sp.select :gender, ["Male", "Female", "Other"], { prompt: "Select your gender" }, { include_blank: false, required: true, id: "editGender" } %>

                            </div>
                            <% end %>
                            </div>
                        </div>

                        <%= s.fields_for :address do |sa| %>
                        
                        <div class="row">
                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :street, "Address" %>
                                <%= sa.text_field :street, id: "editStreet", placeholder: "Enter your full address", required: true %>
                            </div>
                            </div>

                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :city %>
                                <%= sa.text_field :city, id: "editCity", placeholder: "Enter your city", required: true %>
                            </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :state %>
                                <%= sa.text_field :state, id: "editState", placeholder: "Enter your state", required: true %>
                            </div>
                            </div>

                            <div class="col-md-6">
                            <div class="field">
                                <%= sa.label :pin %>
                                <%= sa.text_field :pin, id: "editPin", placeholder: "Enter your PIN code", required: true %>
                            </div>
                            </div>
                        </div>

                        <% end %>
                    <% end %>
                
                <div class="actions">
                    <%= f.button "Cancel", class: "btn btn-danger", type: "button", onclick: "modalClose('editModal')", style: "padding: 10px 20px;" %>
                    <%= f.submit "Update", class: "btn btn-success", style: "padding: 10px 20px;" %>
                </div>
                <% end %>  
            </div>
        </div>
    </div>
</div>

app/views/admins/_subject_wise_students_count.html.erb
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header" style="margin: 0px 0px 10px 20px; display: flex;">
      <h4 class="modal-title">Subject Wise Students Count</h4>
      <span style="margin-left: auto; cursor: pointer;" onclick="modalClose('countModal')"><i class="fa-solid fa-xmark fa-2xl"></i></span>
    </div>
    <div class="modal-body" style="margin: 0px 180px 10px 20px;">
      <table class="table">
        <thead>
          <tr>
            <th>Subject</th>
            <th>Total Count</th>
          </tr>
        </thead>
        <tbody id='table_data'>
        </tbody>
      </table>
      <button type="button" class="btn btn-danger" style="margin-left: 160px;" onclick="modalClose('countModal')">Close</button>
    </div>
  </div>
</div>

app/views/admins/_upload_student_data.html.erb
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header" style="margin: 0px 0px 10px 20px;">
            <div style="display: flex">
                <h5 class="modal-title">Upload Student details</h5>
                <span style="margin-left: auto; cursor: pointer;" onclick="modalClose('uploadModal')">
                    <i class="fa-solid fa-xmark fa-2xl"></i>
                </span>
            </div>
            <span style="font-size: 13px; color: red;">(Format of File : students.csv)</span>
        </div>
        <div class="modal-body">
            <div style="margin: 0px 0px 10px 20px;"> 
                <label for="upload_file">Select File :</label><br />
                <input type="file" id="upload_datafile" multiple name="upload[datafile]" accept=".csv">
            </div>
            <div style="margin-top: 44px;"> 
                <button id="uploadButton" class="btn btn-success" style="margin-right: 10px;">Upload</button>
                <button type="button" class="btn btn-danger" style="margin-left: 10px;" onclick="modalClose('uploadModal')">Close</button>
            </div>
            
            <div style="margin: 0px 0px 10px 20px;">
                <a href="sample_students.csv" download class="edit-profile-link">Download Sample CSV File</a>
            </div>
        </div>
    </div>
</div>


app/views/admins/index.html.erb
<body style="background-color: #fff;">
	<span style="float: right; margin-right: 10px;">Wellcome: Admin | <%= link_to destroy_user_session_path do %>
    Logout
	<% end %></span>
	<div style="margin: 10px 5px; display: flex;">
		<div style="display: flex; margin-right: 15px;">
			<button class="btn btn-primary" onclick="onBtnExport()" ><i class="fa-solid fa-download fa-xs"></i> Export</button>
			<button class="btn btn-default" onclick="onBtnUpload()" ><i class="fa-solid fa-upload fa-xs"></i> Upload</button>
			<button class="btn btn-success" onclick="onBtnAdd()" ><i class="fa-solid fa-user-plus fa-xs"></i> Add</button>
			<button class="btn btn-primary" onclick="onBtnEdit()" ><i class="fa-solid fa-user-edit fa-xs"></i> Edit</button>
			<button class="btn btn-danger" onclick="batchDelete()"><i class="fa-solid fa-user-minus fa-xs"></i> Delete</button>
			<button class="btn btn-success" onclick="batch_student_verify()"><i class="fa-solid fa-user-check fa-xs"></i> Verify</button>
			<button class="btn btn-primary" onclick="subject_wise_students_count()">Subject Wise Students Count</button>
			<div class="input-group rounded" style="margin-top: 20px;display: flex;">
				<input type="search" class="form-control rounded" placeholder="Search in .." aria-label="Search" aria-describedby="search-addon" onkeyup="handleSearchChange(this.value)" />
				<span class="input-group-text border-0" id="search-addon">
					<i class="fas fa-search searchbar"></i>
				</span>
			</div>
		</div>
	</div>
	<div id="loader" class="overlay display-none">
		<img class="img" src="images/loader.gif" />
	</div>
	<div>
		<div id="agGrid" style="height: 550px; width: 100%;" class="ag-theme-balham"></div>
	</div>
	<div id="countModal" class="modal fade">
        <%= render partial: 'admins/subject_wise_students_count' %>        
    </div>
	<div id="uploadModal" class="modal fade">
		<%= render partial: 'admins/upload_student_data' %>        
    </div>
	<div id="addModal" class="modal fade">
		<%= render partial: 'admins/add_student_data' %>        
    </div>
	<div id="editModal" class="modal fade">
		<%= render partial: 'admins/edit_student_data' %>        
    </div>
</body>

<script>
    var columnDefs = [
		{headerName: "", field: "", width: 60, checkboxSelection: true, headerCheckboxSelection: true, cellStyle: { 'text-align':'center','top': '15px' } },
		{headerName: "Image", field: "avatar_url", minWidth: 150, width: 100, cellRenderer: ImageCellRenderer, cellStyle: { 'border': '1px solid grey', 'border-radius': '50%', 'height': '40px', 'width': '40px', 'top': '10px', } },
		{ headerName: "Student Name", field: "name", cellStyle: { 'font-weight': 'bold', 'color': '#666666', 'padding-top': '15px', 'font-size': '15px' } },
		{ headerName: "Email", field: "email", cellStyle: { 'padding-top': '15px', 'color': '#686868' } },
		{ headerName: "Date of Birth", field: "dob", cellStyle: { 'padding-top': '15px', 'color': '#686868' } },
		{ headerName: "Gender", field: "gender", width: 110, cellStyle: { 'padding-top': '15px', 'color': '#686868' } },
		{ headerName: "Address", field: "address", valueGetter: get_full_address, width: 300, cellStyle: { 'padding-top': '15px', 'color': '#686868' } },
		{ headerName: "Status", field: "verified", cellRenderer: VarificationFieldRender, width: 150, cellStyle: { 'padding-top': '15px', 'color': '#686868' } },
		{ headerName: "Subject", field: "subject", width: 150, cellStyle: { 'padding-top': '15px', 'color': '#686868' } }
	];

	function get_full_address(params) {
		return params.data.address.street + ', ' + params.data.address.city + ', ' + params.data.address.state + ', PIN: ' + params.data.address.pin ;
	}
	var gridOptions =
	{
		columnDefs: columnDefs,
		rowData: null,
		enableSorting: true,
		enableFilter: true,
		rowSelection: 'multiple',
		headerHeight: 50,
		rowHeight: 60,
		enableRangeSelection: true,
		enableStatusBar: false,
		// pagination: true,
        suppressExcelExport: true,
		suppressRowClickSelection: true,
		// paginationPageSize: 7,
		onGridReady: function () { },
		components: {
			'imageCellRenderer': ImageCellRenderer,
			'varificationFieldRender': VarificationFieldRender
		},
		onRowClicked: function(event) {
			const node = event.node;
			if (node.isSelected()) {
				node.setSelected(false);
			} else {
				node.setSelected(true);
			}
		}
	};

	function onBtnExport() {
        const columnsToInclude = ['name', 'email', 'dob', 'gender', 'address', 'verified', 'subject'];
		const currentDate = new Date();
		const timestamp = currentDate.toISOString().replace(/:/g, '_').replace(/\..+/, '').replace('T', '_');
		const filenameWithTimestamp = `student_data_${timestamp}.csv`;
        gridOptions.api.exportDataAsCsv({
            columnKeys: columnsToInclude,
            fileName: filenameWithTimestamp
   		 });
    }

    function get_grid_load() {
		createNewDatasource();
    }
    $(document).ready(function () {
        get_grid_load();
        var gridDiv = document.querySelector('#agGrid');
		new agGrid.Grid(gridDiv, gridOptions);
	});

    function createNewDatasource(search_str = '') {
		$('#loader').removeClass('display-none')
		$.ajax({
			type: "get",
			url: "<%= all_user_path %>",
			data: {search: search_str},
			success: function (msg) {
				var grid_data = msg;
				gridOptions.api.setRowData(msg);
				$('#loader').addClass('display-none')
			},
			error: function (error) {
				$('#loader').addClass('display-none')
			}
		});
	}
	
    function VarificationFieldRender() { } 
	function ImageCellRenderer() { }

	VarificationFieldRender.prototype.init = function (params) {
		this.eGui = document.createElement('div');
		var text = "";
		if (params.value){
			text = '<span style="color: #3085d6;">Active</span>';
		}else{
			text = '<span style="color: #d33;">Inactive</span>';
		}
		this.eGui.innerHTML = text;
	};

	VarificationFieldRender.prototype.getGui = function () {
		return this.eGui;
	};

	ImageCellRenderer.prototype.init = function (params) {
        this.eGui = document.createElement('div');
        var src = `<img src= ${params.value} width='40' height='40'>`
        this.eGui.innerHTML = src;
    };

    ImageCellRenderer.prototype.getGui = function () {
        return this.eGui;
    };

	function batch_student_verify() {
		var selected_ids = get_selected_row_ids();
		if(get_selected_row_ids().length > 0){
			handleClickVarification(selected_ids);
		}else {
			alert('Please select at least one student');
		}
	}
	function handleClickVarification(ids) {
		Swal.fire({
			title: `Are you sure you want to verify this student(s)?`,
			text: `This action will verify the student(s).`,
			icon: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#3085d6',
			cancelButtonColor: '#d33',
			confirmButtonText: `Yes, verify it!`
		}).then((result) => {
			if (result.isConfirmed) {
				$('#loader').removeClass('display-none')
				$.ajax({
					type: 'post',
					url: '/user_verify',
					data: { ids: ids },
					headers: {
						'X-CSRF-TOKEN': '<%= form_authenticity_token %>'
					},
					success: function (data) {
						console.log(data.message);
						if (data.message == 'Success') {
						Swal.fire(
							'Verified!',
							'Student(s) has been Verified successfully.',
							'success'
						);
						} else {
						Swal.fire(
							'Already Active!',
							'Student(s) already Verified.',
							'warning'
						);
						}
						get_grid_load();
						$('#loader').addClass('display-none');
					},
					error: function (xhr, status, error) {
						get_grid_load();
						$('#loader').addClass('display-none');
						console.error(xhr.responseText);
					}
				});
			}else {
				get_grid_load();
			}
		});
	}
	
	function batchDelete() {
		var selected_ids = get_selected_row_ids();
		if(get_selected_row_ids().length > 0){
			handleClickDelete(selected_ids);
		}else {
			alert('Please select at least one student');
		}
	}

	function handleClickDelete(ids) {
		Swal.fire({
			title: 'Are you sure?',
			text: 'You won\'t be able to revert this!',
			icon: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#3085d6',
			cancelButtonColor: '#d33',
			confirmButtonText: 'Yes, delete it!'
		}).then((result) => {
			if (result.isConfirmed) {
				$('#loader').removeClass('display-none')
				$.ajax({
					type: 'post',
					url: '/user_delete',
					data: { ids: ids },
					headers: {
						'X-CSRF-TOKEN': '<%= form_authenticity_token %>'
					},
					success: function (data) {
						if (data.message == 'Success') {
							Swal.fire(
								'Deleted!',
								'Student has been deleted.',
								'success'
							);
							}else {
								Swal.fire(
									'Error!',
									'Student(s) did not found.',
									'warning'
								);
							}
						get_grid_load();
						$('#loader').addClass('display-none')
					},
					error: function (xhr, status, error) {
						$('#loader').addClass('display-none');
						console.error(xhr.responseText);
					}
				});
			}
		});
	}

	function get_selected_row_ids(){
		var sel_rows=[]; 
		gridOptions.api.forEachNodeAfterFilterAndSort(function(node, index){
			if (node.selected == true) {
				if (node.data) { 
					sel_rows.push(node.data.id);
				} 
			}
		});
		return sel_rows;
	}

	function subject_wise_students_count() {
		$('#loader').removeClass('display-none')
		$.ajax({
			type: "get",
			url: "subject_wise_students_count",
			success: function (data) {
				$('#loader').addClass('display-none')
				$('#countModal').modal('show');
				var table = document.getElementById('table_data');
				var table_data = "";
				Object.keys(data).forEach(function(key) {
					var value = data[key];
					table_data += '<tr>';
					table_data += '<td>' + key + '</td>';
					table_data += '<td>' + value + '</td>';
					table_data += '</tr>';
				});
				table.innerHTML = table_data;
			},
			error: function (xhr, status, error) {
				$('#loader').addClass('display-none')
				console.error(xhr.responseText);
			}
		});
	}

	function modalClose(id) {
		$(`#${id}`).modal('hide');
	}

	function onBtnUpload(){
		$('#upload_datafile').val('');
		$('#uploadModal').modal('show');
	}

		$('#uploadButton').click(function () {
		const fileInput = document.querySelector('#upload_datafile');
      	const file = fileInput.files[0];
		if (!file) {
			alert('Please select a CSV file.');
			return;
		}
		const formData = new FormData();
		formData.append('csv_file', file);
        $.ajax({
            type: 'POST',
            url: '/save_mass_data_upload',
            data: formData,
            processData: false,
            contentType: false,
			headers: {
                'X-CSRF-TOKEN':'<%= form_authenticity_token %>'
            },
            success: function (response) {
               alert(response);
			   $('#uploadModal').modal('hide');
                get_grid_load();
            },
            error: function (xhr, status, error) {
				console.error(xhr.responseText);
            }
        });
    });

	function onBtnAdd(){
		$('#email').val('');
		$('#name').val('');
		$('#avatar-input').val('');
		$('#bio').val('');
		$('#dob').val('');
		$('#gender').val("");
		$('#street').val('');
		$('#city').val('');
		$('#state').val('');
		$('#pin').val('');
		$('#addModal').modal('show');
	}

	function onBtnEdit() {
		var selected_id = get_selected_row_ids();
		if(get_selected_row_ids().length == 1){
			handleClickEdit(selected_id);
		}else {
			alert('Please select one student');
		}
	}

	function handleClickEdit(id) {
		$.ajax({
            type: 'get',
            url: '/get_student_data',
            data: {id: id},
            success: function (data) {
				$('#userID').val(data.id);
				$('#editEmail').val(data.email);
				$('#editName').val(data.name);
				$('#editBio').val(data.bio);
				$('#editDob').val(data.dob);
				$('#editGender').val(data.gender);
				$('#avatar').val('');
				$('#editStreet').val(data.address.street);
				$('#editCity').val(data.address.city);
				$('#editState').val(data.address.state);
				$('#editPin').val(data.address.pin);
				$('#editModal').modal('show');
            },
            error: function (xhr, status, error) {
				console.error(xhr.responseText);
            }
        });
	}

	function handleSearchChange(value) {
		if (value != ""){
			createNewDatasource(value);
		}else{
			createNewDatasource();
		}
	}
</script>