config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'students',passwords: 'users/passwords'}
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new'
    post 'users/sign_in', to: 'users/sessions#create'
    get 'users/sign_out', to: 'users/sessions#destroy'
    get 'users/sign_up', to: 'users/registrations#new'
    post 'users/sign_up', to: 'users/registrations#create'
    get "student_home", to: 'students#index'
    get "add_subject", to: 'students#add_subject'
    patch "change_subject_request", to: 'students#change_subject_request'
    get "change_password", to: 'users/registrations#change_password'
    patch 'change_my_password', to: 'users/registrations#change_my_password'
    authenticated :user do
      root to: 'application#dashboard'
    end
    unauthenticated do
      root to: "users/sessions#new", as: nil
    end
  end
  
  get "admin_home", to: "admins#index"
  get "all_user", to: "admins#all_user"
  get "subject_wise_students_count", to: "admins#subject_wise_students_count"
  get "user_details", to: "admins#user_details"
  post "user_verify", to: "admins#user_verify"
  post "user_delete", to: "admins#user_delete"
  post "save_mass_data_upload", to: "admins#save_mass_data_upload" 
  post "add_student", to: "admins#add_student"
  get "get_student_data", to: "admins#get_student_data"
  post "update_student", to: "admins#update_student"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_one :profile, dependent: :destroy
  has_one :address, dependent: :destroy
  has_one :subject, dependent: :destroy
  validates :name, presence: true, format: { with: /\A[A-Za-z]+(?: [A-Za-z]+){0,2}\z/, message: "Only alphabets are allowed" }
  validates_associated :profile, :address
end

app/controllers/students_controller.rb
class StudentsController < Devise::RegistrationsController
  before_action :authenticate_user!, except: [:new, :create]
  before_action :configure_permitted_parameters, only: [:create, :update]

  def index
    redirect_to root_path if current_user.role != 'Student'
  end

  def edit
    redirect_to root_path if current_user.role != 'Student'
  end

  def update
    if current_user.role == 'Student'
      user = current_user
      if user.valid_password?(params[:user][:current_password])
        student_params = account_update_params[:student]
        if user.student
          user.student.update(student_params.except(:profile, :address))
          if user.student.profile
            user.student.profile.update(student_params[:profile])
          end
          if user.student.address
            user.student.address.update(student_params[:address])
          end
        end
    
        if user.save
          yield user if block_given?
          if user.active_for_authentication?
            set_flash_message! :notice, :updated
            bypass_sign_in(user, scope: resource_name)
            redirect_to after_update_path_for(user)
          else
            set_flash_message! :notice, :updated_but_must_reconfirm
            expire_data_after_sign_in!
            redirect_to after_update_path_for(user)
          end
        else
          clean_up_passwords user
          set_minimum_password_length
          flash[:alert] = "There was an error with your profile update. Please check the form for errors: #{user.student.errors.full_messages.to_sentence}"
          redirect_to edit_user_registration_path
        end
      else
        flash[:alert] = 'Invalid current password.'
        redirect_to edit_user_registration_path
      end
    else
      redirect_to root_path
    end
  end  

  def add_subject
    redirect_to root_path if current_user.role != 'Student' || !current_user.student.subject.nil?
  end
  
  def change_subject_request
    if current_user.role == 'Student'
      if current_user.valid_password?(params[:user][:current_password])
        subject_params = params[:user][:student][:subject]
        student = current_user.student
        if student.subject.nil?
          subject = Subject.create(name: subject_params[:name], student:  student)
          if subject.save
            redirect_to root_path, notice: 'Subject has been updated.'
          else
            flash[:alert] = 'Failed to update subject.'
            redirect_to add_subject_path
          end
        else
          flash[:alert] = 'You are already selected your subject.'
          redirect_to root_path
        end
      else
        flash[:alert] = 'Invalid current password.'
        redirect_to add_subject_path
      end
    else
      redirect_to root_path
    end
  end  

  def create
    generated_password = Devise.friendly_token.first(8)
    build_resource(sign_up_params.except(:student))
    resource.password = generated_password
    resource.password_confirmation = generated_password
    student_params = sign_up_params[:student]
    resource.build_student(student_params.except(:profile, :address))
    resource.student.build_profile(student_params[:profile])
    resource.student.build_address(student_params[:address])
    resource.student.verified = false
    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :updated_but_must_reconfirm
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      flash[:alert] = "There was an error with your registration. Please check the form for errors: #{resource.student.errors.full_messages.to_sentence}"
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :email,
      student: [
        :name,
        profile: [:avatar, :bio, :dob, :gender],
        address: [:street, :city, :state, :pin]
      ]
    ])
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :current_password,
      student: [
        :name,
        profile: [:avatar, :bio, :dob, :gender],
        address: [:street, :city, :state, :pin]
      ]
    ])
  end

  def after_sign_up_path_for(resource)
    sign_out current_user
    root_path
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/add_subject.html.erb
<style>
  .container {
    justify-content: center;
    align-items: center;
    height: auto;
    width: 350px;
    padding: 20px;
    max-width: 750px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    background-color: #fff;
    border-radius: 5px;
    margin: 10% auto;
  }
</style>
<div class="container">
  <h2>Choose Subject</h2>

  <%= form_for(current_user, url: change_subject_request_path) do |f| %>
   <%= render "devise/shared/error_messages", resource: current_user %>

        <%= f.fields_for :student do |s| %>
            <%= s.fields_for :subject do |sb| %>
                <div class="field">
                        <%= sb.label :name %>
                        <%= sb.select :name, ["JavaScript", "Ruby on Rails", "Python"], prompt: "Choose Your Subject", include_blank: false, required: true %>
                </div>
            <% end %>
        <% end %>
        <div class="field">
        <%= f.label :current_password, 'Current Password' %>
        <%= f.password_field :current_password, required: true %>
        </div>

        <div class="actions">
        <%= f.submit 'Submit' %>
        </div>
    <% end %>
</div>

app/views/students/index.html.erb
<div class="profile-container">
  <div style="text-align: right;">
    <span>Welcome: <%= current_user.student.name %></span> | <%= link_to destroy_user_session_path do %>
    Logout
    <% end %>
  </div>
  <h1>Profile</h1>
  <div class="profile-info">
    <div class="avatar">
      <% if current_user.student.profile.avatar.attached? %>
          <%= image_tag current_user.student.profile.avatar, style: "border-radius: 50%;", size: "100x100" %>
      <% else %>
        <%= image_tag "https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg", style: "border-radius: 50%;", size: "100x100" %>
      <% end %>
    </div>
    <div class="user-details">
      <p>Name: <%= current_user.student.name %></p>
      <p>Date of Birth: <%= current_user.student.profile.dob %></p>
      <p>Gender: <%= current_user.student.profile.gender %></p>
      <p>Address: <%= current_user.student.address.city %></p>
      <p>Email: <%= current_user.email %></p>
      <p>Subject: <%= current_user.student.subject.name %></p>
      <div style="display: flex;">
        <%= link_to 'Edit Profile', edit_user_registration_path, class: 'edit-profile-link' %>
        <%= link_to 'Change Password', change_password_path, class: 'edit-profile-link' %>
      </div>
    </div>
  </div>
</div>